name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose

  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # Step to set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.x"  # Specify the Python version

    # Step to install dependencies from requirements.txt
    - name: Install Python dependencies
      run: pip install -r requirements.txt

    - name: Run Unit tests
      run: cargo test --verbose

    - name: Run Integration tests
      run: python -m pytest
