name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: extractions/setup-just@v2
    - uses: actions/setup-python@v4
      with:
        python-version: "3.x"

    - name: Setup
      run: just setup

    - name: Build
      run: just build

    - name: Run Unit tests
      run: just unit-tests

    - name: Run Integration tests
      run: just integration-tests
